package:
   name: intake_hypothetic
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..
git:
  depth: false

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - intake>=0.2
    - python
    - scipy
    - iris
    - iris_hypothetic
    - boto3

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - py.test --verbose

about:
  home: https://github.com/informaticslab/intake-hypothetic
  license: BSD
  license_file: LICENSE
  summary: |
    iris hypothetic plugins for Intake
